'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.1
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System

Namespace My.Resources
    
    'This class was auto-generated by the StronglyTypedResourceBuilder
    'class via a tool like ResGen or Visual Studio.
    'To add or remove a member, edit your .ResX file then rerun ResGen
    'with the /str option, or rebuild your VS project.
    '''<summary>
    '''  A strongly-typed resource class, for looking up localized strings, etc.
    '''</summary>
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0"),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute(),  _
     Global.Microsoft.VisualBasic.HideModuleNameAttribute()>  _
    Friend Module Resources
        
        Private resourceMan As Global.System.Resources.ResourceManager
        
        Private resourceCulture As Global.System.Globalization.CultureInfo
        
        '''<summary>
        '''  Returns the cached ResourceManager instance used by this class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend ReadOnly Property ResourceManager() As Global.System.Resources.ResourceManager
            Get
                If Object.ReferenceEquals(resourceMan, Nothing) Then
                    Dim temp As Global.System.Resources.ResourceManager = New Global.System.Resources.ResourceManager("CyberPet.Resources", GetType(Resources).Assembly)
                    resourceMan = temp
                End If
                Return resourceMan
            End Get
        End Property
        
        '''<summary>
        '''  Overrides the current thread's CurrentUICulture property for all
        '''  resource lookups using this strongly typed resource class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Property Culture() As Global.System.Globalization.CultureInfo
            Get
                Return resourceCulture
            End Get
            Set
                resourceCulture = value
            End Set
        End Property
        
        Friend ReadOnly Property Body_1() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Body_1", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Body_1ASLEEP() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Body_1ASLEEP", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Body_1AWAKE() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Body_1AWAKE", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Body0() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Body0", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Body0ASLEEP() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Body0ASLEEP", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Body0AWAKE() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Body0AWAKE", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Body1() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Body1", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Body1ASLEEP() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Body1ASLEEP", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Body1AWAKE() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Body1AWAKE", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Body2() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Body2", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Body2ASLEEP() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Body2ASLEEP", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Body2AWAKE() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Body2AWAKE", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Body3() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Body3", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Body3ASLEEP() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Body3ASLEEP", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Body3AWAKE() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Body3AWAKE", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Body4() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Body4", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Body4ASLEEP() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Body4ASLEEP", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Body4AWAKE() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Body4AWAKE", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Body5() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Body5", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Body5ASLEEP() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Body5ASLEEP", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Body5AWAKE() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Body5AWAKE", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Body6() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Body6", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Body6ASLEEP() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Body6ASLEEP", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Body6AWAKE() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Body6AWAKE", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Body7() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Body7", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Body7ASLEEP() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Body7ASLEEP", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Body7AWAKE() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Body7AWAKE", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Body8() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Body8", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Body8ASLEEP() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Body8ASLEEP", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Body8AWAKE() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Body8AWAKE", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Body9() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Body9", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Body9ASLEEP() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Body9ASLEEP", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Body9AWAKE() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Body9AWAKE", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property DefaultMouth() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("DefaultMouth", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property EvilMouth() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("EvilMouth", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property GoodMouth() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("GoodMouth", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
    End Module
End Namespace
